services:
  db:
    image: kadai/db
    build: ./db
    container_name: mysql_db
    ports:
      - "3306:3306"  # ポートの公開
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ../db/init:/docker-entrypoint-initdb.d
    
  backend:
    image: kadai/backend
    build: ./backend
    container_name: fastapi_backend
    working_dir: /usr/src/app
    ports:
      - 5080:80
    stdin_open: true
    tty: true
    volumes:
      - ../backend:/usr/src/app
    depends_on:
      - db
    command: /bin/bash

volumes:
  mysql_data:
